kind = "web"
previewPath = "/"
title = "NourStore"
version = "1.0.0"
id = "artifacts/nourstore"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23624

[services.development]
run = "pnpm --filter @workspace/nourstore run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nourstore", "run", "build" ]
serve = "static"
publicDir = "artifacts/nourstore/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23624"
BASE_PATH = "/"
